---
- hosts: localhost
  become: yes

  tasks:
    - name: Install the offical DEB from Mozilla
      block:
        - ansible.builtin.file:
            path: /etc/apt/keyrings
            mode: '0755'
          register: keyrings
        - ansible.builtin.get_url:
            url: https://packages.mozilla.org/apt/repo-signing-key.gpg
            dest: "{{ keyrings.path }}/packages.mozilla.org.asc"
            checksum: sha256:3ce6a27fe0538464191eebb9ff1a0b8a269af16d872524822b25198328263e84
          register: signing_key
        - ansible.builtin.apt_repository:
            repo: "deb [signed-by={{ signing_key.dest }}] https://packages.mozilla.org/apt mozilla main"
            state: present
            filename: mozilla.list
        - ansible.builtin.template:
            src: mozillateam.j2
            dest: /etc/apt/preferences.d/mozillateam.pref
        - ansible.builtin.apt:
              update_cache: yes
    - name: Remove the Snap version of Firefox
      community.general.snap:
          name: firefox
          state: absent
    - name: Update and install Firefox
      ansible.builtin.apt:
          update_cache: yes
          name: firefox
          state: latest